### ISSUE TITLE
[Feature Request] Add functions for stage standings and playoffs standings

### ISSUE THREAD

**Issue by LuqmanAlSaba** [ryanoconr/overwatchleague#3]
The current getStandings() function returns the league standings. Add functions that return the stage standings and playoffs standings.

**Comment by oconr** [comment]
Overwatch have changed the structure of the standings data for 2019 but I haven't updated it yet. The new structure is more organised but not as sorted as it was. I'm going to look through their structure and create some functions that should help with getting the data for the individual stages and playoffs.

**Comment by oconr** [comment]
The latest update should hopefully be more helpful for getting specific stage standings but the standings that are returned might not be an exact match to the Overwatch League website as they are using head-to-head data to decide which teams are placed higher when there are tied positions and this data is simply returned as null from the API. I've done the best I can to mirror the methods they use to calculate the standings though.
